// Generated by Manus game sharing.
import { spawnSync } from 'node:child_process'
import { basename } from 'node:path'
import { assembleThreejsShareSite, GameSharingValidationError } from './metadata.mjs'

// Publication metadata is public project content; no runtime credentials are embedded here.
const publicationOrigin = "https://quadpoint-ntm5zkmj.manus.game"
const outputDirectory = "dist"
const projectTitle = "QuadPoint 4D"
// Run the original script through the invoking package manager, preserving argument quoting.
const packageManager = process.env.npm_execpath
if (!packageManager) throw new Error('Run sharing through the package.json build script')
// A nested npm invocation can inherit the outer pnpm user agent.
const npm = ['npm', 'npm-cli.js', 'npm.js'].includes(basename(packageManager))
const result = spawnSync(process.execPath, [packageManager, 'run', "manus:build-source", ...(npm ? ['--'] : []), ...process.argv.slice(2)], { stdio: 'inherit' })
if (result.error) throw result.error
if (result.status !== 0) process.exit(result.status ?? 1)
try {
  const snapshot = assembleThreejsShareSite(process.cwd(), outputDirectory, { publicationOrigin, projectTitle })
  if (snapshot?.assets.og) console.log('[sharing] OG image included in the game build')
} catch (error) {
  const reason = error instanceof GameSharingValidationError ? error.message
    : error instanceof SyntaxError ? 'game-sharing.json must contain valid JSON'
    : error?.code === 'ENOENT' ? 'A configured PNG asset or build output is missing'
    : 'Check file access and the configured build output'
  console.warn('[sharing] ' + reason + '. Could not include the OG image. Check game-sharing.json and its PNG assets, then prepare sharing and rebuild. The game build will continue.')
}
