// Generated by Manus game sharing.
import { createHash, randomBytes } from 'node:crypto'
import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { extname, join } from 'node:path'

export const GAME_SHARING_FILE = 'game-sharing.json'
export const MAX_SHARE_IMAGE_BYTES = 8 * 1024 * 1024
const MAX_SNAPSHOT_BYTES = 128 * 1024
const DIGEST = /^sha256:[a-f0-9]{64}$/
const PROJECT_IMAGE = /^assets\/(?!.*(?:^|\/)\.\.?(?:\/|$))[^\\%?#\u0000-\u001f]+\.png$/i
const PLATFORMS = ['x', 'facebook', 'reddit', 'discord']
export class GameSharingValidationError extends Error {}
const fail = message => { throw new GameSharingValidationError(message || 'Game sharing metadata is invalid') }
const digest = bytes => 'sha256:' + createHash('sha256').update(bytes).digest('hex')
const record = value => value !== null && typeof value === 'object' && !Array.isArray(value)

function exact(value, keys, message = 'Game sharing metadata is invalid') {
  if (!record(value) || Object.keys(value).some(key => !keys.includes(key))) fail(message)
}
function text(value, maximum, required = false) {
  if (typeof value !== 'string' || value.length > maximum || (required && !value.trim()) || /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value)) fail()
  return value
}
function origin(value) {
  let parsed
  try { parsed = new URL(value) } catch { fail('Game sharing publication URL is invalid; prepare sharing again') }
  if (parsed.protocol !== 'https:' || parsed.origin !== value || parsed.username || parsed.password || parsed.port ||
      !/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(parsed.hostname) || /(?:^|\.)(?:localhost|local|internal)$/.test(parsed.hostname)) {
    fail('Game sharing publication URL is invalid; prepare sharing again')
  }
  return parsed.origin
}
function captions(value = {}) {
  exact(value, PLATFORMS)
  const result = {}
  for (const platform of PLATFORMS) if (value[platform] !== undefined) result[platform] = text(value[platform], 4000)
  return result
}
function projectImage(value) {
  if (typeof value !== 'string' || value.length > 512 || !PROJECT_IMAGE.test(value) || value.split('/').some(part => !part || part === '.' || part === '..')) fail('Game sharing image must be a PNG under assets/')
  return value
}

/** Editable project content. Missing optional values use the UI/build defaults. */
export function parseProjectShare(value) {
  exact(value, ['schemaVersion', 'title', 'description', 'defaultCaptions', 'assets'])
  if (value.schemaVersion !== 2) fail('game-sharing.json must use schemaVersion 2')
  exact(value.assets ?? {}, ['og', 'favicon'])
  return {
    schemaVersion: 2,
    ...(value.title !== undefined ? { title: text(value.title, 120, true) } : {}),
    ...(value.description !== undefined ? { description: text(value.description, 1000) } : {}),
    defaultCaptions: captions(value.defaultCaptions),
    assets: {
      ...(value.assets?.og !== undefined ? { og: projectImage(value.assets.og) } : {}),
      ...(value.assets?.favicon !== undefined ? { favicon: projectImage(value.assets.favicon) } : {}),
    },
  }
}
export function canonicalProjectShare(value) { return JSON.stringify(parseProjectShare(value), null, 2) + '\n' }

function releaseAsset(value) {
  exact(value, ['digest', 'path', 'mime', 'width', 'height', 'sizeBytes', 'sourcePath'])
  if (!DIGEST.test(value.digest) || value.path !== `share/${value.digest.slice(7)}.png` || value.mime !== 'image/png' ||
      !Number.isSafeInteger(value.width) || value.width < 1 || !Number.isSafeInteger(value.height) || value.height < 1 || value.width * value.height > 16 * 1024 * 1024 ||
      !Number.isSafeInteger(value.sizeBytes) || value.sizeBytes < 1 || value.sizeBytes > MAX_SHARE_IMAGE_BYTES ||
      (value.sourcePath !== undefined && !PROJECT_IMAGE.test(value.sourcePath))) fail('Game sharing release image is invalid')
  return { digest: value.digest, path: value.path, mime: value.mime, width: value.width, height: value.height, sizeBytes: value.sizeBytes,
    ...(value.sourcePath !== undefined ? { sourcePath: value.sourcePath } : {}) }
}
function parseLegacyAsset(value) {
  exact(value, ['assetRef', 'digest', 'path', 'mime', 'width', 'height', 'sizeBytes'])
  const parsed = releaseAsset({ digest: value.digest, path: value.path, mime: value.mime, width: value.width, height: value.height, sizeBytes: value.sizeBytes })
  if (typeof value.assetRef !== 'string' || !/^[a-zA-Z0-9_-]{1,128}$/.test(value.assetRef)) fail('Legacy Game sharing image is invalid')
  return { assetRef: value.assetRef, ...parsed }
}

/** Immutable checkpoint content. Version 1 remains readable without its former DB row. */
export function parseShareSnapshot(value) {
  if (value?.schemaVersion === 1) {
    exact(value, ['schemaVersion', 'resourceId', 'shareRevisionId', 'shareRevision', 'contentHash', 'publicationOrigin', 'title', 'description', 'defaultCaptions', 'assets'])
    if (typeof value.resourceId !== 'string' || !/^[a-zA-Z0-9_-]{1,128}$/.test(value.resourceId) || typeof value.shareRevisionId !== 'string' ||
        !/^[a-zA-Z0-9_-]{1,128}$/.test(value.shareRevisionId) || !Number.isSafeInteger(value.shareRevision) || value.shareRevision < 1 || !DIGEST.test(value.contentHash)) fail('Legacy Game sharing snapshot is invalid')
    exact(value.assets, ['og', 'favicon'])
    return { schemaVersion: 1, resourceId: value.resourceId, shareRevisionId: value.shareRevisionId, shareRevision: value.shareRevision,
      contentHash: value.contentHash, publicationOrigin: origin(value.publicationOrigin), title: text(value.title, 120, true), description: text(value.description, 1000),
      defaultCaptions: captions(value.defaultCaptions), assets: { og: parseLegacyAsset(value.assets.og), favicon: parseLegacyAsset(value.assets.favicon) } }
  }
  exact(value, ['schemaVersion', 'publicationOrigin', 'title', 'description', 'defaultCaptions', 'assets'])
  if (value.schemaVersion !== 2) fail('Game sharing snapshot version is unsupported')
  exact(value.assets ?? {}, ['og', 'favicon'])
  return { schemaVersion: 2, publicationOrigin: origin(value.publicationOrigin), title: text(value.title, 120, true), description: text(value.description, 1000),
    defaultCaptions: captions(value.defaultCaptions), assets: {
      ...(value.assets?.og ? { og: releaseAsset(value.assets.og) } : {}),
      ...(value.assets?.favicon ? { favicon: releaseAsset(value.assets.favicon) } : {}),
    } }
}
export function canonicalShareSnapshot(snapshot) { return JSON.stringify(parseShareSnapshot(snapshot), null, 2) + '\n' }

function regularFile(root, parts, maximum) {
  let current = realpathSync(root)
  for (let index = 0; index < parts.length; index++) {
    current = join(current, parts[index])
    const info = lstatSync(current)
    if (info.isSymbolicLink() || (index < parts.length - 1 ? !info.isDirectory() : !info.isFile() || info.size > maximum)) fail('Game sharing file is not a regular bounded file')
  }
  return readFileSync(current)
}
export function readProjectShare(root) {
  try { return parseProjectShare(JSON.parse(regularFile(root, [GAME_SHARING_FILE], MAX_SNAPSHOT_BYTES).toString('utf8'))) }
  catch (error) { if (error.code === 'ENOENT') return null; throw error }
}
export function ensureProjectShare(root) {
  const current = readProjectShare(root)
  if (current) return current
  const created = parseProjectShare({ schemaVersion: 2, defaultCaptions: {}, assets: {} })
  atomicWrite(realpathSync(root), GAME_SHARING_FILE, canonicalProjectShare(created))
  return created
}
export function readPreparedShare(root) {
  try { return parseShareSnapshot(JSON.parse(regularFile(root, [GAME_SHARING_FILE], MAX_SNAPSHOT_BYTES).toString('utf8'))) }
  catch (error) { if (error.code === 'ENOENT') return null; throw error }
}
export function verifyShareImage(bytes, expected) {
  if (!Buffer.isBuffer(bytes) || bytes.length !== expected.sizeBytes || bytes.length > MAX_SHARE_IMAGE_BYTES || bytes.length < 33 || digest(bytes) !== expected.digest ||
      !bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) || bytes.readUInt32BE(8) !== 13 || bytes.toString('ascii', 12, 16) !== 'IHDR' ||
      bytes.readUInt32BE(16) !== expected.width || bytes.readUInt32BE(20) !== expected.height) fail('Game sharing image bytes do not match the checkpoint')
  return bytes
}
function directory(parent, name) {
  const result = join(parent, name)
  if (!existsSync(result)) mkdirSync(result)
  const info = lstatSync(result)
  if (!info.isDirectory() || info.isSymbolicLink() || realpathSync(result) !== result) fail('Game sharing output directory is invalid')
  return result
}
function atomicWrite(parent, name, bytes) {
  const destination = join(parent, name)
  if (existsSync(destination)) { const info = lstatSync(destination); if (!info.isFile() || info.isSymbolicLink()) fail('Game sharing output path is invalid') }
  const temporary = join(parent, `.game-share-${randomBytes(12).toString('hex')}.tmp`)
  try { writeFileSync(temporary, bytes, { flag: 'wx', mode: 0o644 }); renameSync(temporary, destination) }
  finally { rmSync(temporary, { force: true }) }
}

const CONTEXT_FILE = 'context.json'
export function installSharePreparation(root, input) {
  exact(input, ['publicationOrigin'])
  const value = { publicationOrigin: origin(input.publicationOrigin) }
  const cache = directory(directory(realpathSync(root), '.manus-webdev'), 'game-share')
  atomicWrite(cache, CONTEXT_FILE, JSON.stringify(value, null, 2) + '\n')
  return value
}
export function readSharePreparation(root) {
  try {
    const value = JSON.parse(regularFile(root, ['.manus-webdev', 'game-share', CONTEXT_FILE], 4096).toString('utf8'))
    exact(value, ['publicationOrigin'])
    return { publicationOrigin: origin(value.publicationOrigin) }
  } catch (error) {
    if (error.code === 'ENOENT') return null
    // Private preparation state is optional; its I/O failures must use the sharing fallback too.
    fail('Game sharing preparation could not be read; run game/sharing/prepare again')
  }
}
function projectTitle(root) {
  const source = regularFile(root, ['project.godot'], 4 * 1024 * 1024).toString('utf8')
  const value = /^config\/name="((?:[^"\\]|\\.)*)"\s*$/m.exec(source)?.[1]
  if (!value) return 'Game'
  try { return text(JSON.parse(`"${value}"`), 120, true) } catch { return 'Game' }
}
function projectDescription(root) {
  const source = regularFile(root, ['project.godot'], 4 * 1024 * 1024).toString('utf8')
  const value = /^config\/description="((?:[^"\\]|\\.)*)"\s*$/m.exec(source)?.[1]
  if (!value) return ''
  try { return text(JSON.parse(`"${value}"`), 1000) } catch { return '' }
}
function projectAsset(root, sourcePath) {
  const bytes = regularFile(root, sourcePath.split('/'), MAX_SHARE_IMAGE_BYTES)
  if (extname(sourcePath).toLowerCase() !== '.png' || bytes.length < 33 || !bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) ||
      bytes.readUInt32BE(8) !== 13 || bytes.toString('ascii', 12, 16) !== 'IHDR') fail(`Game sharing image is not a valid PNG: ${sourcePath}`)
  const width = bytes.readUInt32BE(16), height = bytes.readUInt32BE(20)
  if (!width || !height || width * height > 16 * 1024 * 1024) fail(`Game sharing image dimensions are invalid: ${sourcePath}`)
  const hash = digest(bytes)
  return { bytes, release: { digest: hash, path: `share/${hash.slice(7)}.png`, mime: 'image/png', width, height, sizeBytes: bytes.length, sourcePath } }
}
export function materializeShareSnapshot(root, preparation, defaults = {}) {
  const project = readProjectShare(root)
  if (!project) return null
  if (!preparation) fail('Run game/sharing/prepare before building a project that has game-sharing.json')
  const assets = {}, bytes = {}
  for (const purpose of ['og', 'favicon']) {
    const sourcePath = project.assets[purpose]
    if (!sourcePath) continue
    const image = projectAsset(root, sourcePath)
    assets[purpose] = image.release
    bytes[purpose] = image.bytes
  }
  const snapshot = parseShareSnapshot({ schemaVersion: 2, publicationOrigin: preparation.publicationOrigin,
    title: project.title ?? defaults?.title ?? projectTitle(root), description: project.description ?? defaults?.description ?? projectDescription(root), defaultCaptions: project.defaultCaptions, assets })
  return { snapshot, bytes }
}

export function addExportedFavicon(sharing, exportRoot) {
  if (!sharing || sharing.snapshot.assets.favicon) return sharing
  let bytes
  try { bytes = regularFile(exportRoot, ['index.icon.png'], MAX_SHARE_IMAGE_BYTES) }
  catch (error) { if (error.code === 'ENOENT') return sharing; throw error }
  if (bytes.length < 33 || !bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) ||
      bytes.readUInt32BE(8) !== 13 || bytes.toString('ascii', 12, 16) !== 'IHDR') fail('Game exported favicon is not a valid PNG')
  const width = bytes.readUInt32BE(16), height = bytes.readUInt32BE(20)
  if (!width || !height || width * height > 16 * 1024 * 1024) fail('Game exported favicon dimensions are invalid')
  const hash = digest(bytes)
  return {
    snapshot: parseShareSnapshot({ ...sharing.snapshot, assets: { ...sharing.snapshot.assets,
      favicon: { digest: hash, path: `share/${hash.slice(7)}.png`, mime: 'image/png', width, height, sizeBytes: bytes.length } } }),
    bytes: { ...sharing.bytes, favicon: bytes },
  }
}

const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll("'", '&#39;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
const decode = value => value.replace(/&(?:#(x[0-9a-f]+|[0-9]+)|(amp|quot|apos|lt|gt));/gi, (all, numeric, named) => {
  if (numeric) { const code = parseInt(numeric[0].toLowerCase() === 'x' ? numeric.slice(1) : numeric, numeric[0].toLowerCase() === 'x' ? 16 : 10); return code <= 0x10ffff ? String.fromCodePoint(code) : all }
  return { amp: '&', quot: '"', apos: "'", lt: '<', gt: '>' }[named.toLowerCase()]
})
// Use the same head/token rules as the writer; comments and raw-text bodies are not metadata.
export function shareHtmlDefaults(html) {
  const tag = htmlTags(), defaults = {}
  let inHead = false, match
  while ((match = tag.exec(html))) {
    const token = match[0], name = /^<\/?([a-zA-Z][a-zA-Z0-9:-]*)/.exec(token)?.[1]?.toLowerCase(), closing = token.startsWith('</')
    if (name === 'head') {
      if (closing) break
      inHead = true
    }
    if (!closing && ['script', 'style', 'textarea', 'title'].includes(name)) {
      const close = new RegExp(`</${name}\\s*>`, 'gi'); close.lastIndex = tag.lastIndex
      const end = close.exec(html)
      if (!end) break
      if (inHead && name === 'title' && defaults.title === undefined) {
        const title = decode(html.slice(tag.lastIndex, end.index)).trim()
        if (title) defaults.title = title.slice(0, 120)
      }
      tag.lastIndex = close.lastIndex
    } else if (inHead && !closing && name === 'meta') {
      const attrs = htmlAttributes(token)
      if (attrs.name?.toLowerCase() === 'description' && attrs.content !== undefined && defaults.description === undefined) defaults.description = attrs.content.slice(0, 1000)
    }
  }
  return defaults
}
function htmlTags() { return /<!--[\s\S]*?-->|<![^>]*>|<\/?[a-zA-Z][a-zA-Z0-9:-]*(?:[^"'<>]|"[^"]*"|'[^']*')*>/g }
function htmlAttributes(token) {
  const attrs = Object.create(null), attr = /([^\s"'<>/=]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s<>]+))/g
  let found
  while ((found = attr.exec(token))) {
    const key = found[1].toLowerCase()
    if (!Object.hasOwn(attrs, key)) attrs[key] = decode(found[2] ?? found[3] ?? found[4])
  }
  return attrs
}
const managedMeta = new Set(['description', 'og:type', 'og:title', 'og:description', 'og:url', 'og:image', 'og:image:width', 'og:image:height', 'og:image:type', 'og:image:alt', 'twitter:card', 'twitter:title', 'twitter:description', 'twitter:image', 'twitter:image:alt'])
const BEGIN = '<!-- manus:game-sharing:start -->', END = '<!-- manus:game-sharing:end -->'
function shareTags(snapshot, fields) {
  const includes = key => !fields || fields.has(key)
  const meta = (key, value) => !includes(key) ? '' : `<meta ${key.startsWith('og:') ? 'property' : 'name'}="${key}" content="${escape(value)}">`
  const tags = [fields ? '' : BEGIN]
  const { favicon, og } = snapshot.assets
  if (includes('title')) tags.push(`<title>${escape(snapshot.title)}</title>`)
  if (favicon && includes('favicon')) tags.push(`<link rel="icon" type="image/png" href="./${favicon.path}">`, `<link rel="apple-touch-icon" href="./${favicon.path}">`)
  tags.push(meta('description', snapshot.description), meta('og:type', 'website'), meta('og:title', snapshot.title), meta('og:description', snapshot.description), meta('og:url', snapshot.publicationOrigin + '/'))
  if (og) tags.push(meta('og:image', `${snapshot.publicationOrigin}/${og.path}`), meta('og:image:width', og.width), meta('og:image:height', og.height), meta('og:image:type', og.mime), meta('og:image:alt', snapshot.title))
  tags.push(meta('twitter:card', og ? 'summary_large_image' : 'summary'), meta('twitter:title', snapshot.title), meta('twitter:description', snapshot.description))
  if (og) tags.push(meta('twitter:image', `${snapshot.publicationOrigin}/${og.path}`), meta('twitter:image:alt', snapshot.title))
  if (!fields) tags.push(END)
  return tags.filter(Boolean).join('\n') + '\n'
}
export function applyShareHtml(html, input, { preserveUnconfiguredFavicon = false, fields } = {}) {
  const snapshot = parseShareSnapshot(input)
  if (typeof html !== 'string' || Buffer.byteLength(html) > 8 * 1024 * 1024) fail('Game sharing HTML is invalid')
  const selected = fields ? new Set(fields) : null
  const metadata = selected ?? managedMeta
  const tag = htmlTags()
  let cursor = 0, result = '', inserted = false, inHead = false, match
  while ((match = tag.exec(html))) {
    result += html.slice(cursor, match.index)
    const token = match[0], name = /^<\/?([a-zA-Z][a-zA-Z0-9:-]*)/.exec(token)?.[1]?.toLowerCase(), closing = token.startsWith('</')
    let remove = false
    if (selected && inHead && (token === BEGIN || token === END)) { cursor = tag.lastIndex; continue }
    if (token === BEGIN && inHead) {
      const end = html.indexOf(END, tag.lastIndex)
      if (end < 0) fail('Game sharing HTML markers are incomplete')
      cursor = end + END.length; if (html[cursor] === '\n') cursor++; tag.lastIndex = cursor; continue
    }
    if (name === 'head') {
      if (closing) { if (!inHead || inserted) fail(); result += shareTags(snapshot, selected); inserted = true; inHead = false }
      else { if (inHead || inserted) fail(); inHead = true }
    }
    if (!closing && inHead && (name === 'meta' || name === 'link')) {
      const attrs = htmlAttributes(token)
      for (const key of ['name', 'property', 'rel']) if (attrs[key]) attrs[key] = attrs[key].toLowerCase()
      remove = name === 'meta' ? metadata.has(attrs.name) || metadata.has(attrs.property)
        : (selected ? selected.has('favicon') : !preserveUnconfiguredFavicon || Boolean(snapshot.assets.favicon)) && String(attrs.rel || '').split(/\s+/).some(value => ['icon', 'apple-touch-icon', 'apple-touch-icon-precomposed'].includes(value))
    }
    if (!closing && ['script', 'style', 'textarea', 'title'].includes(name)) {
      const close = new RegExp(`</${name}\\s*>`, 'gi'); close.lastIndex = tag.lastIndex
      const end = close.exec(html); if (!end) fail()
      const finish = close.lastIndex
      if (!(name === 'title' && inHead && (!selected || selected.has('title')))) result += html.slice(match.index, finish)
      cursor = finish; tag.lastIndex = finish; continue
    }
    if (!remove) result += token
    cursor = tag.lastIndex
  }
  if (!inserted || inHead) fail('Game sharing HTML has no valid head')
  return result + html.slice(cursor)
}
export function assembleShareSite(_root, site, materialized, options) {
  if (!materialized) return
  const snapshot = parseShareSnapshot(materialized.snapshot ?? materialized), realSite = realpathSync(site), shared = directory(realSite, 'share')
  for (const purpose of ['og', 'favicon']) {
    const expected = snapshot.assets[purpose]
    if (expected) atomicWrite(shared, expected.digest.slice(7) + '.png', verifyShareImage(materialized.bytes?.[purpose], expected))
  }
  atomicWrite(realSite, GAME_SHARING_FILE, canonicalShareSnapshot(snapshot))
  if (!options?.preserveHtml) atomicWrite(realSite, 'index.html', applyShareHtml(regularFile(site, ['index.html'], 8 * 1024 * 1024).toString('utf8'), snapshot, options))
}
export function verifyShareSite(root, site) {
  const published = readPreparedShare(site)
  if (!published) return null
  for (const expected of Object.values(published.assets)) verifyShareImage(regularFile(site, expected.path.split('/'), MAX_SHARE_IMAGE_BYTES), expected)
  const html = regularFile(site, ['index.html'], 8 * 1024 * 1024).toString('utf8')
  if (applyShareHtml(html, published) !== html) fail('Game sharing HTML does not match its checkpoint metadata')
  if (published.schemaVersion === 1) {
    const legacy = readPreparedShare(root)
    if (!legacy || canonicalShareSnapshot(legacy) !== canonicalShareSnapshot(published)) fail('Legacy Game sharing snapshot is incomplete')
  }
  return published
}

/** Shared by the portable Web build hook and the immutable browser snapshot builder. */
export function assembleThreejsShareSite(projectDir, outputDirectory, preparation) {
  const root = realpathSync(projectDir), project = readProjectShare(root)
  if (!project) return null
  if (typeof outputDirectory !== 'string' || !/^[\w./-]+$/.test(outputDirectory) ||
      outputDirectory.split('/').some(part => !part || part === '.' || part === '..')) fail('Sharing output must be a project directory')
  let output = root
  for (const part of outputDirectory.split('/')) {
    output = join(output, part)
    const stat = lstatSync(output)
    if (stat.isSymbolicLink() || !stat.isDirectory()) fail('Sharing output must be a project directory')
  }
  const html = regularFile(output, ['index.html'], 8 * 1024 * 1024).toString('utf8')
  const pkg = JSON.parse(regularFile(root, ['package.json'], 1024 * 1024).toString('utf8'))
  const sharing = materializeShareSnapshot(root, preparation, {
    title: preparation?.projectTitle?.trim() || (typeof pkg.name === 'string' ? pkg.name.trim().slice(0, 120) : '') || 'Game',
    description: typeof pkg.description === 'string' ? pkg.description.slice(0, 1000) : '',
    ...shareHtmlDefaults(html),
  })
  // Without a cover, change only explicit metadata. Keep the author's other
  // tags (including externally hosted OG images) intact.
  const fields = project.assets.og ? undefined : [
    ...(project.title !== undefined ? ['title', 'og:title', 'twitter:title'] : []),
    ...(project.description !== undefined ? ['description', 'og:description', 'twitter:description'] : []),
    ...(project.assets.favicon ? ['favicon'] : []),
  ]
  assembleShareSite(root, output, sharing, { preserveUnconfiguredFavicon: true, fields, preserveHtml: fields?.length === 0 })
  return sharing.snapshot
}
